### ISSUE TITLE
Plugin won't load on the latest Java version

### ISSUE THREAD

**Issue by GalaxiaOwner** [Minkizz/BotMaker#5]
[09:42:03] [Server thread/ERROR]: Could not load 'plugins\BotMaker (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/minkizz/botmaker/BotMaker has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.UnsupportedClassVersionError: me/minkizz/botmaker/BotMaker has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_191]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_191]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_191]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_191]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_191]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_191]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_191]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.jar:git-Spigot-c3c767f-33d5de3]
	... 6 more

**Comment by Minkizz** [comment]
Fixed, enjoy!
